"""
PDF Report Generator for Personal Organizer.
Uses ReportLab to generate clean, professional executive summaries & action plans.
"""

import io
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, KeepTogether
)
from reportlab.pdfgen import canvas


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas for dynamic 'Page X of Y' footers."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b"))

        # Header (pages 2+)
        if self._pageNumber > 1:
            self.drawString(40, 760, "Personal Organizer — AI Executive Summary & Plan")
            self.drawRightString(572, 760, datetime.now().strftime("%B %d, %Y"))
            self.setStrokeColor(colors.HexColor("#e2e8f0"))
            self.setLineWidth(0.5)
            self.line(40, 752, 572, 752)

        # Footer
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawString(40, 30, "Generated by Personal Organizer • AI-Powered Executive Planner")
        self.drawRightString(572, 30, page_str)
        self.setStrokeColor(colors.HexColor("#e2e8f0"))
        self.setLineWidth(0.5)
        self.line(40, 42, 572, 42)
        self.restoreState()


def generate_executive_pdf(
    username: str,
    ai_summary: dict,
    goals: list,
    tasks: list,
    events: list,
    meds: list,
    notes: list
) -> bytes:
    """
    Builds a multi-page PDF executive brief containing AI insights, goals,
    tasks, calendar schedule, and care routines.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=40,
        rightMargin=40,
        topMargin=40,
        bottomMargin=50,
    )

    styles = getSampleStyleSheet()

    # Custom typography styles
    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#0f172a"),
        spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        "DocSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#64748b"),
        spaceAfter=14,
    )
    h1_style = ParagraphStyle(
        "Heading1_Custom",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=16,
        textColor=colors.HexColor("#1e293b"),
        spaceBefore=14,
        spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "Body_Custom",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=13.5,
        textColor=colors.HexColor("#334155"),
    )
    callout_style = ParagraphStyle(
        "Callout_Text",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=14,
        textColor=colors.HexColor("#1e293b"),
    )
    table_cell_style = ParagraphStyle(
        "TableCell",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=11.5,
        textColor=colors.HexColor("#1e293b"),
    )
    table_header_style = ParagraphStyle(
        "TableHeader",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=12,
        textColor=colors.white,
    )

    story = []

    # 1. Header Banner
    story.append(Paragraph("Personal Organizer — AI Executive Briefing", title_style))
    meta_text = f"Prepared for: <b>{username}</b> &nbsp;|&nbsp; Date: <b>{datetime.now().strftime('%B %d, %Y')}</b> &nbsp;|&nbsp; Engine: <b>{ai_summary.get('ai_source', 'AI Engine')}</b>"
    story.append(Paragraph(meta_text, subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#2563eb"), spaceAfter=14))

    # 2. Executive Synthesis Box
    exec_summary_text = ai_summary.get("executive_overview") or ai_summary.get("summary") or "Comprehensive action plan and productivity breakdown for active goals, upcoming tasks, and scheduled commitments."
    callout_data = [
        [
            Paragraph(f"<b>🎯 Executive Synthesis:</b><br/>{exec_summary_text}", callout_style)
        ]
    ]
    callout_table = Table(callout_data, colWidths=[532])
    callout_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#eff6ff")),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#bfdbfe")),
        ('LEFTPADDING', (0,0), (-1,-1), 12),
        ('RIGHTPADDING', (0,0), (-1,-1), 12),
        ('TOPPADDING', (0,0), (-1,-1), 10),
        ('BOTTOMPADDING', (0,0), (-1,-1), 10),
    ]))
    story.append(callout_table)
    story.append(Spacer(1, 12))

    # Key Productivity Highlights / Metrics
    score = ai_summary.get("productivity_score", "92/100")
    focus_focus = ai_summary.get("top_priority", "Execute high-impact goals and daily time-blocks.")
    metrics_data = [
        [
            Paragraph(f"<b>Productivity Score</b><br/><font size=14 color='#2563eb'><b>{score}</b></font>", callout_style),
            Paragraph(f"<b>Top Priority Focus</b><br/>{focus_focus}", callout_style),
            Paragraph(f"<b>Active Items</b><br/>{len(tasks)} Tasks • {len(goals)} Goals • {len(events)} Events", callout_style),
        ]
    ]
    metrics_table = Table(metrics_data, colWidths=[130, 260, 142])
    metrics_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#f8fafc")),
        ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor("#e2e8f0")),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#e2e8f0")),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING', (0,0), (-1,-1), 8),
        ('RIGHTPADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(metrics_table)
    story.append(Spacer(1, 14))

    # 3. Goals & Key Milestones
    if goals:
        story.append(Paragraph("🎯 Strategic Goals & Roadmaps", h1_style))
        goal_rows = [[
            Paragraph("Goal Title", table_header_style),
            Paragraph("Timeframe", table_header_style),
            Paragraph("Target Date", table_header_style),
            Paragraph("Status", table_header_style),
        ]]
        for g in goals[:8]:
            goal_rows.append([
                Paragraph(f"<b>{g.get('title', '')}</b><br/><font color='#64748b' size=7.5>{g.get('description', '')[:90]}</font>", table_cell_style),
                Paragraph(g.get("timeframe", "3 months"), table_cell_style),
                Paragraph(g.get("target_date", "Ongoing"), table_cell_style),
                Paragraph(f"<font color='#2563eb'><b>{g.get('status', 'Active').title()}</b></font>", table_cell_style),
            ])
        goal_table = Table(goal_rows, colWidths=[240, 95, 105, 92])
        goal_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#1e293b")),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#f8fafc")]),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
            ('TOPPADDING', (0,0), (-1,-1), 5),
            ('BOTTOMPADDING', (0,0), (-1,-1), 5),
            ('LEFTPADDING', (0,0), (-1,-1), 6),
            ('RIGHTPADDING', (0,0), (-1,-1), 6),
        ]))
        story.append(goal_table)
        story.append(Spacer(1, 14))

    # 4. Actionable Tasks
    if tasks:
        story.append(Paragraph("📋 Priority Task Action Items", h1_style))
        task_rows = [[
            Paragraph("Task", table_header_style),
            Paragraph("Priority", table_header_style),
            Paragraph("Status", table_header_style),
            Paragraph("Due Date", table_header_style),
        ]]
        for t in tasks[:15]:
            p_color = "#dc2626" if t.get("priority") == "high" else ("#d97706" if t.get("priority") == "medium" else "#64748b")
            s_color = "#059669" if t.get("status") == "completed" else ("#2563eb" if t.get("status") == "in_progress" else "#64748b")
            task_rows.append([
                Paragraph(f"<b>{t.get('title', '')}</b><br/><font color='#64748b' size=7.5>{t.get('description', '')[:80]}</font>", table_cell_style),
                Paragraph(f"<font color='{p_color}'><b>{t.get('priority', 'medium').upper()}</b></font>", table_cell_style),
                Paragraph(f"<font color='{s_color}'><b>{t.get('status', 'pending').replace('_', ' ').title()}</b></font>", table_cell_style),
                Paragraph(t.get("due_date", "No date"), table_cell_style),
            ])
        task_table = Table(task_rows, colWidths=[250, 75, 105, 102])
        task_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#1e293b")),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#f8fafc")]),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
            ('TOPPADDING', (0,0), (-1,-1), 4.5),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4.5),
            ('LEFTPADDING', (0,0), (-1,-1), 6),
            ('RIGHTPADDING', (0,0), (-1,-1), 6),
        ]))
        story.append(task_table)
        story.append(Spacer(1, 14))

    # 5. Calendar Schedule & Time-Blocks
    if events:
        story.append(Paragraph("📅 Schedule & Time-Blocks", h1_style))
        event_rows = [[
            Paragraph("Event / Time Block", table_header_style),
            Paragraph("Date", table_header_style),
            Paragraph("Time Slot", table_header_style),
        ]]
        for e in events[:10]:
            event_rows.append([
                Paragraph(f"<b>{e.get('title', '')}</b><br/><font color='#64748b' size=7.5>{e.get('description', '')[:80]}</font>", table_cell_style),
                Paragraph(e.get("date", ""), table_cell_style),
                Paragraph(f"{e.get('time_start', '')} - {e.get('time_end', '')}", table_cell_style),
            ])
        event_table = Table(event_rows, colWidths=[310, 110, 112])
        event_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#1e293b")),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#f8fafc")]),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
            ('TOPPADDING', (0,0), (-1,-1), 4.5),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4.5),
            ('LEFTPADDING', (0,0), (-1,-1), 6),
            ('RIGHTPADDING', (0,0), (-1,-1), 6),
        ]))
        story.append(event_table)
        story.append(Spacer(1, 14))

    # 6. Care & Medication Regimen (if present)
    if meds:
        story.append(Paragraph("💊 Care & Medication Tracker", h1_style))
        med_rows = [[
            Paragraph("Medication", table_header_style),
            Paragraph("Patient", table_header_style),
            Paragraph("Dosage & Frequency", table_header_style),
            Paragraph("Scheduled Times", table_header_style),
        ]]
        for m in meds[:8]:
            med_rows.append([
                Paragraph(f"<b>{m.get('medication_name', '')}</b>", table_cell_style),
                Paragraph(m.get("patient_name", ""), table_cell_style),
                Paragraph(f"{m.get('dosage', '')} ({m.get('frequency', '')})", table_cell_style),
                Paragraph(f"<b>{m.get('times', '')}</b>", table_cell_style),
            ])
        med_table = Table(med_rows, colWidths=[150, 110, 142, 130])
        med_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#0f766e")),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#f0fdfa")]),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#99f6e4")),
            ('TOPPADDING', (0,0), (-1,-1), 4.5),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4.5),
            ('LEFTPADDING', (0,0), (-1,-1), 6),
            ('RIGHTPADDING', (0,0), (-1,-1), 6),
        ]))
        story.append(med_table)
        story.append(Spacer(1, 14))

    # 7. AI Recommendations & Strategic Guidance
    recommendations = ai_summary.get("recommendations", [])
    if recommendations:
        story.append(Paragraph("💡 AI Strategic Recommendations & Next Steps", h1_style))
        rec_data = []
        for r in recommendations[:5]:
            rec_data.append([
                Paragraph(f"• <b>{r}</b>", callout_style)
            ])
        rec_table = Table(rec_data, colWidths=[532])
        rec_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#fefce8")),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#fde047")),
            ('LEFTPADDING', (0,0), (-1,-1), 10),
            ('RIGHTPADDING', (0,0), (-1,-1), 10),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ]))
        story.append(rec_table)

    # Build the document with two-pass canvas
    doc.build(story, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer.getvalue()
